/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimelineIdRouteImport } from './routes/$timelineId'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SShareIdRouteImport } from './routes/s.$shareId'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates.$templateId'
import { Route as ApiShareShareIdRouteImport } from './routes/api.share.$shareId'
import { Route as ApiShareNewRouteImport } from './routes/api.share.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineIdRoute = TimelineIdRouteImport.update({
  id: '/$timelineId',
  path: '/$timelineId',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SShareIdRoute = SShareIdRouteImport.update({
  id: '/s/$shareId',
  path: '/s/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareShareIdRoute = ApiShareShareIdRouteImport.update({
  id: '/api/share/$shareId',
  path: '/api/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareNewRoute = ApiShareNewRouteImport.update({
  id: '/api/share/new',
  path: '/api/share/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$timelineId': typeof TimelineIdRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/s/$shareId': typeof SShareIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/': typeof TemplatesIndexRoute
  '/api/share/$shareId': typeof ApiShareShareIdRoute
  '/api/share/new': typeof ApiShareNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$timelineId': typeof TimelineIdRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/s/$shareId': typeof SShareIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates': typeof TemplatesIndexRoute
  '/api/share/$shareId': typeof ApiShareShareIdRoute
  '/api/share/new': typeof ApiShareNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$timelineId': typeof TimelineIdRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/s/$shareId': typeof SShareIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/templates/': typeof TemplatesIndexRoute
  '/api/share/$shareId': typeof ApiShareShareIdRoute
  '/api/share/new': typeof ApiShareNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$timelineId'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/s/$shareId'
    | '/templates/$templateId'
    | '/templates/'
    | '/api/share/$shareId'
    | '/api/share/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$timelineId'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/s/$shareId'
    | '/templates/$templateId'
    | '/templates'
    | '/api/share/$shareId'
    | '/api/share/new'
  id:
    | '__root__'
    | '/'
    | '/$timelineId'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/s/$shareId'
    | '/templates/$templateId'
    | '/templates/'
    | '/api/share/$shareId'
    | '/api/share/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TimelineIdRoute: typeof TimelineIdRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SShareIdRoute: typeof SShareIdRoute
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  ApiShareShareIdRoute: typeof ApiShareShareIdRoute
  ApiShareNewRoute: typeof ApiShareNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$timelineId': {
      id: '/$timelineId'
      path: '/$timelineId'
      fullPath: '/$timelineId'
      preLoaderRoute: typeof TimelineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$shareId': {
      id: '/s/$shareId'
      path: '/s/$shareId'
      fullPath: '/s/$shareId'
      preLoaderRoute: typeof SShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/$shareId': {
      id: '/api/share/$shareId'
      path: '/api/share/$shareId'
      fullPath: '/api/share/$shareId'
      preLoaderRoute: typeof ApiShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/new': {
      id: '/api/share/new'
      path: '/api/share/new'
      fullPath: '/api/share/new'
      preLoaderRoute: typeof ApiShareNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TimelineIdRoute: TimelineIdRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SShareIdRoute: SShareIdRoute,
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  ApiShareShareIdRoute: ApiShareShareIdRoute,
  ApiShareNewRoute: ApiShareNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
