/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimelineIdRouteImport } from './routes/$timelineId'
import { Route as SShareIdRouteImport } from './routes/s.$shareId'
import { Route as ApiShareShareIdRouteImport } from './routes/api.share.$shareId'
import { Route as ApiShareNewRouteImport } from './routes/api.share.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineIdRoute = TimelineIdRouteImport.update({
  id: '/$timelineId',
  path: '/$timelineId',
  getParentRoute: () => rootRouteImport,
} as any)
const SShareIdRoute = SShareIdRouteImport.update({
  id: '/s/$shareId',
  path: '/s/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareShareIdRoute = ApiShareShareIdRouteImport.update({
  id: '/api/share/$shareId',
  path: '/api/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareNewRoute = ApiShareNewRouteImport.update({
  id: '/api/share/new',
  path: '/api/share/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$timelineId': typeof TimelineIdRoute
  '/s/$shareId': typeof SShareIdRoute
  '/api/share/$shareId': typeof ApiShareShareIdRoute
  '/api/share/new': typeof ApiShareNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$timelineId': typeof TimelineIdRoute
  '/s/$shareId': typeof SShareIdRoute
  '/api/share/$shareId': typeof ApiShareShareIdRoute
  '/api/share/new': typeof ApiShareNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$timelineId': typeof TimelineIdRoute
  '/s/$shareId': typeof SShareIdRoute
  '/api/share/$shareId': typeof ApiShareShareIdRoute
  '/api/share/new': typeof ApiShareNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$timelineId'
    | '/s/$shareId'
    | '/api/share/$shareId'
    | '/api/share/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$timelineId'
    | '/s/$shareId'
    | '/api/share/$shareId'
    | '/api/share/new'
  id:
    | '__root__'
    | '/'
    | '/$timelineId'
    | '/s/$shareId'
    | '/api/share/$shareId'
    | '/api/share/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TimelineIdRoute: typeof TimelineIdRoute
  SShareIdRoute: typeof SShareIdRoute
  ApiShareShareIdRoute: typeof ApiShareShareIdRoute
  ApiShareNewRoute: typeof ApiShareNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$timelineId': {
      id: '/$timelineId'
      path: '/$timelineId'
      fullPath: '/$timelineId'
      preLoaderRoute: typeof TimelineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$shareId': {
      id: '/s/$shareId'
      path: '/s/$shareId'
      fullPath: '/s/$shareId'
      preLoaderRoute: typeof SShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/$shareId': {
      id: '/api/share/$shareId'
      path: '/api/share/$shareId'
      fullPath: '/api/share/$shareId'
      preLoaderRoute: typeof ApiShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/new': {
      id: '/api/share/new'
      path: '/api/share/new'
      fullPath: '/api/share/new'
      preLoaderRoute: typeof ApiShareNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TimelineIdRoute: TimelineIdRoute,
  SShareIdRoute: SShareIdRoute,
  ApiShareShareIdRoute: ApiShareShareIdRoute,
  ApiShareNewRoute: ApiShareNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
